"""Add pessoa to endereco.

Revision ID: 80a3e11a36f0
Revises: e932b46e6eb1
Create Date: 2023-04-24 16:58:42.044811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a3e11a36f0'
down_revision = 'e932b46e6eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pessoa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pessoa', ['pessoa_id'], ['id'])

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('senha')

    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pessoa_id')

    # ### end Alembic commands ###
